import React, { Component } from "react";
import { Image, Typography, Divider } from "antd";
import linearCircuitCourseImg from "../../../components/images/educationImages/linearCircuitCourseImg.jpg";
import { NavigationBar } from "../../../components/Navigation/NavigationBar";
import "./index.css";

const { Title, Paragraph, Text, Link } = Typography;

class Ece140 extends Component {
  render() {
    return (
      <div className="ece140-homePage">
        <NavigationBar />
        <div className="ece140-header">ECE140 & ECE240: Circuits</div>
        <div className="ece140-content">
          <img src={linearCircuitCourseImg} style={{ height: "25%", width: "100%" }} />
          <Typography>
            <Title>ECE140: Linear Circuits</Title>
            <Title level={3}>Course Overview</Title>
            <Paragraph>
              ECE140 introduces basic electric citcuit elements including resistors, capacitors, inductors and sources. Additionally, I also learn analysis techniques for both DC and AC linear
              circuits.
            </Paragraph>
            <Title level={3}>Course Content</Title>
            <Paragraph>
                <ul>
                    <li>Current, Voltage, Power</li>
                    <li>Circuit Elements and their pplications, Ohm's Law, KCL, KVL</li>
                    <li>Series and Parallel Resistors, Nodal Analysis</li>
                    <li>Mesh Analysis</li>
                    <li>Linearity and superposition, Source transformation</li>
                    <li>Thevenin and Norton Equivalents, Maximum Power Transfer</li>
                    <li>Operational Amplifiers</li>
                    <li>Capacitors and Inductors</li>
                    <li>First-Order Citcuits (Transient Analysis)</li>
                    <li>Sinusoidal Steady-State Analysis</li>
                    <li>AC Power Analysis</li>
                </ul>
            </Paragraph>
            <Title>ECE240: Electronic Circuits</Title>
            <Title level={3}>Course Overview</Title>
            <Paragraph>
              ECE240 introduces the electronic circuits and devices used to perform signal processing. In signal processing, this course teaches how to design and build circuits to extract useful
              information encoded in electrical signals or to modify certain properties of electrical signals in some way. Electrical signals may be "analog" (continuous in time and amplitude) or
              "digital" (continuous in time but take on only certain amplitude values).
            </Paragraph>
            <Paragraph>
              The content in ECE240 can be used to process electrical signals generated by transducers, wireless communication devices, microprocessors and storage media
            </Paragraph>
            <Title level={3}>Course Content</Title>
            <Title level={5}>Op amps</Title>
            <Paragraph>
              <ul>
                <li>Ideal and non-ideal (practical) op amps</li>
                <li>Amplifiers built using op amps (difference amp, instrumentation amp, etc)</li>
              </ul>
            </Paragraph>
            <Title level={5}>Frequency response of 1st-order circuits</Title>
            <Paragraph>
              <ul>
                <li>Passive and active electronic filters</li>
                <li>Relationship between transient response and frequency response</li>
                <li>Design amplifiers to meet specifications</li>
              </ul>
            </Paragraph>
            <Title level={5}>Diodes</Title>
            <Paragraph>
              <ul>
                <li>Non-linear electronic devices built using semiconductors</li>
                <li>Used for power delivery/conversion circuits (eg: AC/DC converters)</li>
              </ul>
            </Paragraph>
            <Title level={5}>2nd-order circuits</Title>
            <Paragraph>
              <ul>
                <li>RLC Circuits</li>
                <li>Exhibit energy transfer between L and C</li>
                <li>Transient and frequency responses</li>
              </ul>
            </Paragraph>
            <Title level={5}>Transistors</Title>
            <Paragraph>
              <ul>
                <li>Digital switch for building logic gates, microprocessors, GPUs, memories, DSPs, etc</li>
                <li>Analog amplifier for building op amps, audio circuits, communication circuits, sensor interfaces, etc</li>
              </ul>
            </Paragraph>
          </Typography>
        </div>
      </div>
    );
  }
}

export default Ece140;
